# Dockerfile kibana
#Jordi Amela

# S'estableix la imatge font del kibana oficial
FROM kibana

# Es defineix el autor
MAINTAINER jordi amela

# Es copia el fitxer de configuració del kibana
COPY kibana.yml /opt/kibana/config/kibana.yml

# S'obra el port per defecte que utilitza el kibana
EXPOSE 5601

