##############################################################################
# Dockerfile per executar un logstash
# Basada en una imatge...
##############################################################################

# Establece la imagen de base a utilizar para Ubuntu
FROM elasticsearch:2.3

# Establece el autor (maintainer) del archivo (tu nombre - el autor del archivo)
MAINTAINER jordi amela

# Actualización de la lista de fuentes del repositorio de aplicaciones por defecto
COPY configuració elasticsearch

RUN instalar plugins grafics..



# Puerto para exponer (por defecto: 11211)
#EXPOSE 11211
